// admin-app/src/views/Login.vue
<template>
  <div class="login-page">
    <div class="login-card">
      <h1>AIStory Admin</h1>
      <form @submit.prevent="handleLogin">
        <input v-model="email" type="email" placeholder="Email" required class="input" />
        <input v-model="password" type="password" placeholder="Password" required class="input" />
        <button type="submit" class="btn-primary" :disabled="loading">{{ loading ? 'Logging in...' : 'Log In' }}</button>
        <p v-if="error" class="error">{{ error }}</p>
      </form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import axios from 'axios';

const router = useRouter();
const email = ref('');
const password = ref('');
const loading = ref(false);
const error = ref('');

const handleLogin = async () => {
  loading.value = true; error.value = '';
  try {
    const r = await axios.post('http://127.0.0.1:8000/api/v1/auth/login', { email: email.value, password: password.value });
    localStorage.setItem('admin_token', r.data.data.token);
    router.push('/dashboard');
  } catch (e) { error.value = e.response?.data?.error || 'Login failed'; }
  finally { loading.value = false; }
};
</script>

<style scoped>
.login-page { min-height: 100vh; display: flex; align-items: center; justify-content: center; background: #0f172a; }
.login-card { width: 100%; max-width: 400px; padding: 2.5rem; background: rgba(255,255,255,0.05); border-radius: 1rem; border: 1px solid rgba(255,255,255,0.1); }
h1 { font-size: 1.5rem; font-weight: 700; margin-bottom: 1.5rem; text-align: center; }
.input { width: 100%; padding: 0.75rem; margin-bottom: 1rem; background: rgba(255,255,255,0.1); border: 1px solid rgba(255,255,255,0.2); border-radius: 0.5rem; color: #fff; font-size: 0.875rem; }
.input:focus { outline: none; border-color: #a855f7; }
.btn-primary { width: 100%; padding: 0.75rem; background: #7c3aed; border: none; border-radius: 0.5rem; color: #fff; font-weight: 600; cursor: pointer; }
.btn-primary:disabled { opacity: 0.5; cursor: not-allowed; }
.error { margin-top: 1rem; padding: 0.75rem; background: rgba(239,68,68,0.1); border: 1px solid rgba(239,68,68,0.3); border-radius: 0.5rem; color: #f87171; font-size: 0.875rem; }
</style>

// user-app/src/pages/Login.jsx
import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

export default function Login() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault(); setError('');
    try { await login(email, password); navigate('/dashboard'); } catch (err) { setError(err.response?.data?.error || 'Login failed'); }
  };

  return (
    <div className="min-h-screen bg-slate-900 flex items-center justify-center px-4">
      <div className="w-full max-w-md p-8 bg-white/5 rounded-2xl border border-white/10">
        <h1 className="text-3xl font-bold text-white text-center mb-8">Welcome Back</h1>
        {error && <div className="mb-4 p-3 bg-red-500/10 border border-red-500/30 rounded-lg text-red-400 text-sm">{error}</div>}
        <form onSubmit={handleSubmit} className="space-y-5">
          <div><label className="block text-sm text-white/60 mb-1">Email</label><input type="email" value={email} onChange={e => setEmail(e.target.value)} required className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white focus:outline-none focus:border-purple-500" /></div>
          <div><label className="block text-sm text-white/60 mb-1">Password</label><input type="password" value={password} onChange={e => setPassword(e.target.value)} required className="w-full px-4 py-3 bg-white/10 border border-white/20 rounded-lg text-white focus:outline-none focus:border-purple-500" /></div>
          <button type="submit" className="w-full py-3 bg-purple-600 rounded-lg font-semibold hover:bg-purple-700 transition">Log In</button>
        </form>
        <p className="text-center text-white/40 text-sm mt-6">Don't have an account? <Link to="/register" className="text-purple-400 hover:underline">Register</Link></p>
      </div>
    </div>
  );
}
